kind: CronJob
apiVersion: batch/v1
metadata:
  name: cronjob-summary-downtime
  namespace: monitoring
  uid: 95da0102-8cd0-4dc8-ac5d-0f867a8978ee
  generation: 1
  creationTimestamp: "2026-05-08T02:43:10Z"
  annotations:
    description: ""
spec:
  schedule: "5 17 * * *"
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: cronjob-summary-downtime
            version: v1
          annotations:
            pod.cce.io/tags: '{"CCE-Cluster-ID":"576526f0-2caf-11f1-a899-0255ac1001c6","CCE-Namespace":"monitoring"}'
            resource.cce.io/instance-type: general-computing
        spec:
          containers:
            - name: container-cronjob-summary-downtime
              image: swr.ap-southeast-2.myhuaweicloud.com/developer-schoolbright-images/development-image-sb-web-helper:latest
              command:
                - /bin/bash
              args:
                - "-c"
                - bun run cronjobs/scripts/downtime/summary-downtime.ts
              env:
                - name: PAAS_APP_NAME
                  value: cronjob-summary-downtime
                - name: PAAS_NAMESPACE
                  value: monitoring
                - name: PAAS_PROJECT_ID
                  value: 0b3163d313800ff52f20c014ee5ca721
                - name: DATABASE_TIMESHEET_URL
                  value: postgresql://timesheet:T1me5h%40%40t%402025@10.0.0.148:9499/TimeSheet_System?schema=public
              resources:
                limits:
                  cpu: 250m
                  memory: 512Mi
                requests:
                  cpu: 250m
                  memory: 512Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          securityContext: {}
          imagePullSecrets:
            - name: default-secret
          schedulerName: default-scheduler
          dnsConfig:
            options:
              - name: single-request-reopen
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 20
