export const API_URL = {
    DEV_PAYMENT_API_URL:
        process.env.NEXT_PUBLIC_DEVELOPMENT_PAYMENT_API_URL ?? "error",
    PROD_PAYMENT_API_URL:
        process.env.NEXT_PUBLIC_PRODUCTION_PAYMENT_API_URL ?? "error",
    PROD_SB_API_URL: process.env.NEXT_PUBLIC_PRODUCTION_SB_API_URL ?? "error",
    DEV_SB_API_URL: process.env.NEXT_PUBLIC_DEVELOPMENT_SB_API_URL ?? "error",
    PROD_HARDWARE_API_URL:
        process.env.NEXT_PUBLIC_PRODUCTION_HARDWARE_API_URL ?? "error",
    DEV_HARDWARE_API_URL:
        process.env.NEXT_PUBLIC_DEVELOPMENT_HARDWARE_API_URL ?? "error",
    PROD_ADMIN_JABJAI_API_URL:
        process.env.NEXT_PUBLIC_ADMIN_JABJAI_URL ?? "error",
    PROD_ACCOUNTING_WEB_URL: process.env.NEXT_PUBLIC_PRODUCTION_ACCOUNTING_WEB_URL ?? "error",
    PROD_ACADEMIC_WEB_URL: process.env.NEXT_PUBLIC_PRODUCTION_ACADEMIC_WEB_URL ?? "error",
    PROD_CANTEEN_WEB_URL: process.env.NEXT_PUBLIC_PRODUCTION_CANTEEN_WEB_URL ?? "error",
    PROD_SCHOOLBUS_WEB_URL: process.env.NEXT_PUBLIC_PRODUCTION_SCHOOLBUS_WEB_URL ?? "error",
    PROD_LIBRARY_WEB_URL: process.env.NEXT_PUBLIC_PRODUCTION_LIBRARY_WEB_URL ?? "error",
    PROD_MARK_ACTIVITY_WEB_URL: process.env.NEXT_PUBLIC_PRODUCTION_MARK_ACTIVITY_WEB_URL ?? "error",
    PROD_PAYMENT_GATEWAY_API_URL: process.env.NEXT_PUBLIC_PRODUCTION_PAYMENT_GATEWAY_WEB_URL ?? "error"
} as const;

export type ApiUrlKey = keyof typeof API_URL;
